import ContactForm from "@/components/contact-form";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact - Get in touch",
  description: "Generated by create next app",
};

const ContactSection = () => {
  return (
    <div className="bg-background py-15 sm:py-20 w-full font-geistMono text-foreground">
      <ContactForm />
    </div>
  );
};

export default ContactSection;
