import ContactForm from "@/components/contact-form";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Contact - Get in touch",
  description: "Generated by create next app",
};

const ContactSection = () => {
  return (
    <div
      className="bg-background fill-mode-both py-15 sm:py-20 w-full font-geistMono text-foreground animate-in duration-700 ease-linear fade-in"
    >
      <ContactForm />
    </div>
  );
};

export default ContactSection;
