import type { Metadata } from "next";
import { Geist_Mono, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";

import { Navbar } from "@/components/common/Navbar";
import Footer from "@/components/common/Footer";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import Quotes from "@/components/common/Quotes";
import BackToTop from "@/components/common/BackToTop";



const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibmPlexSans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geistMono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Kunal - A Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning style={{ scrollBehavior: "smooth" }}>
      <body
        className={`${geistMono.variable} ${ibmPlexSans.variable}  antialiased `}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
          <BackToTop />
          <Quotes />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
